import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
process.env.EXPLORE_INDIA_DB=':memory:';
process.env.ADMIN_EMAIL='browser-owner@example.com';
process.env.ADMIN_PASSWORD='BrowserTestPassword2026';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {app}=await import('../backend/server.js');
const server=await new Promise((resolve,reject)=>{const listener=app.listen(0,'127.0.0.1',()=>resolve(listener));listener.on('error',reject);});
const base=`http://127.0.0.1:${server.address().port}`;
let browser;
try{
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  const page=await browser.newPage({viewport:{width:1280,height:900}});
  await page.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`${base}/destination.html?slug=karnataka`);
  await page.locator('#destinationContent').waitFor({state:'visible'});
  assert.match(await page.locator('#destinationName').textContent(),/Karnataka/);
  assert.ok(await page.locator('#places .guide-card').count()>=10);
  await page.locator('#places .guide-card-open').first().click();
  assert.equal(await page.locator('#guideDialog').evaluate(node=>node.open),true);
  await page.locator('#closeGuide').click();
  await page.goto(`${base}/culture.html`);
  await page.locator('.culture-page-hero').waitFor();
  await page.waitForTimeout(300);
  const broken=await page.locator('img:not(.culture-dialog-image)').evaluateAll(images=>images.filter(image=>image.complete&&image.naturalWidth===0).map(image=>image.getAttribute('src')));
  assert.deepEqual(broken,[]);
  await page.goto(`${base}/auth.html`);
  await page.locator('[data-panel="register"]').click();
  await page.locator('#registerForm [name="name"]').fill('Browser Traveller');
  await page.locator('#registerForm [name="email"]').fill('browser-traveller@example.com');
  await page.locator('#registerForm [name="password"]').fill('BrowserTestPassword2026');
  await page.locator('#registerForm button[type="submit"]').click();
  await page.waitForURL(/states\.html|profile\.html|index\.html|planner\.html/,{timeout:10000});
  await page.goto(`${base}/planner.html`);
  await page.locator('#destinationChoices input').first().waitFor();
  await page.locator('#tripForm [name="title"]').fill('Karnataka discovery');
  await page.locator('#tripForm [name="origin"]').fill('Bengaluru');
  await page.locator('#tripForm [name="days"]').fill('7');
  await page.locator('#destinationChoices input').first().check();
  await page.locator('#previewTrip').click();
  await page.locator('#previewDays .planner-day').first().waitFor();
  assert.equal(await page.locator('#previewDays .planner-day').count(),7);
  await page.locator('#saveTrip').click();
  await page.locator('.saved-trip').first().waitFor();
  assert.equal(await page.locator('.saved-trip').count(),1);
  await page.goto(`${base}/admin.html`);
  await page.waitForURL(/auth\.html/);
  assert.deepEqual(errors,[]);
  console.log('Browser smoke passed: destination, detail view, account, itinerary preview and save.');
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
