const cultureDetails={
  Diwali:{label:"Festival of lights",intro:"Diwali is celebrated in many parts of India as a time for light, family visits, prayer and new beginnings.",facts:["Homes are decorated with diyas, lamps and rangoli.","Families share sweets, gifts and festive meals.","Dates change each year because the festival follows a lunar calendar."]},
  Holi:{label:"Spring festival",intro:"Holi welcomes spring with colour, music and gatherings that bring friends, families and neighbourhoods together.",facts:["The evening before is marked by Holika Dahan bonfires in many communities.","The following day is known for colour, water, music and sweets.","Local customs differ widely across regions, including Braj and Bengal traditions."]},
  Onam:{label:"Kerala harvest",intro:"Onam is Kerala’s major harvest celebration, remembered through floral art, shared meals, games and performances.",facts:["Pookalam flower carpets welcome guests at homes and public spaces.","The Onasadya is a generous vegetarian feast traditionally served on a banana leaf.","Boat races and cultural programmes are important public celebrations."]},
  Pongal:{label:"Tamil harvest",intro:"Pongal is a four-day Tamil harvest festival centred on gratitude to the sun, cattle, farmers and nature.",facts:["Sweet Pongal is cooked until it boils over, symbolising abundance.","Kolam designs decorate entrances during the celebrations.","Mattu Pongal honours cattle and their role in agricultural life."]},
  Navratri:{label:"Nine nights",intro:"Navratri is observed across India through devotion, dance, fasting and regional forms of celebration.",facts:["In Gujarat, Garba and Dandiya Raas create evening community gatherings.","Many households honour different forms of the goddess over nine nights.","Celebration styles and food traditions vary by region."]},
  "Durga Puja":{label:"Eastern India",intro:"Durga Puja transforms neighbourhoods into spaces for worship, art, music, food and shared celebration, especially in West Bengal.",facts:["Elaborate temporary pandals host artistically designed installations.","The festival celebrates Durga’s victory over Mahishasura.","The final immersion marks a joyful and emotional farewell."]},
  "Eid-ul-Fitr":{label:"Faith and community",intro:"Eid-ul-Fitr marks the end of Ramadan with prayer, generosity, visits and celebratory meals.",facts:["Many people begin with congregational Eid prayers.","Giving and sharing are central to the occasion.","Festive tables often include sevaiyan and regional specialities."]},
  Baisakhi:{label:"Punjab harvest",intro:"Baisakhi is a spring harvest festival in Punjab and an important day in Sikh tradition.",facts:["It is celebrated with bhangra, gidda, fairs and seasonal food.","For Sikhs, it commemorates the founding of the Khalsa in 1699.","Community gatherings combine faith, music and gratitude for the harvest."]},
  "Mysuru Dasara":{label:"Karnataka royal festival",intro:"Mysuru Dasara is Karnataka’s celebrated ten-day festival, known for illuminated heritage buildings, music and processions.",facts:["The Jamboo Savari procession is the best-known public event.","Mysuru Palace is illuminated on festival evenings.","The festival reflects traditions of the former Mysore kingdom."]},
  Ugadi:{label:"Karnataka new year",intro:"Ugadi is the New Year celebration observed in Karnataka, Andhra Pradesh and Telangana.",facts:["Families prepare bevu-bella, a mixture that symbolises life’s varied experiences.","Homes are decorated with mango leaves and rangoli.","The day is marked by new clothes, family meals and fresh beginnings."]},
  Kambala:{label:"Coastal Karnataka",intro:"Kambala is a traditional buffalo race held in the wet paddy fields of coastal Karnataka’s Tulunadu region.",facts:["It is staged in a waterlogged track and draws large local crowds.","The event is associated with rural community life and agricultural landscapes.","Today, organised meets showcase both tradition and athletic spectacle."]},
  Kashmiri:{label:"Himalayan table",intro:"Kashmiri food balances warming spices, slow-cooked dishes, rice and fragrant tea traditions.",facts:["Wazwan is a ceremonial multi-course meal with deep cultural importance.","Kahwa is an aromatic tea often flavoured with saffron, cardamom and almonds.","Vegetarian dishes such as haak and nadru are also central to regional cooking."]},
  Rajasthani:{label:"Desert table",intro:"Rajasthani cuisine uses grains, pulses, dairy and preserved ingredients shaped by a dry climate.",facts:["Dal baati churma is one of its best-known combinations.","Gatte, ker sangri and spicy pickles are regional favourites.","Thalis bring several flavours and textures together on one plate."]},
  Gujarati:{label:"Western table",intro:"Gujarati food is known for its varied thalis, seasonal vegetables, lentils, breads and balance of sweet, sour and savoury flavours.",facts:["A thali may include dal, kadhi, shaak, breads, rice and snacks.","Undhiyu is a much-loved winter vegetable dish.","Farsan snacks such as dhokla and khandvi are popular across the state."]},
  Kerala:{label:"Kerala table",intro:"Kerala’s food is shaped by coconut, curry leaves, rice, seafood and a long spice-trading history.",facts:["Sadya is a festive vegetarian banquet served on a banana leaf.","Appam, puttu and fish curry reflect different regional kitchens.","Malabar cuisine is known for layered biryanis and rich coastal flavours."]},
  Bengali:{label:"Eastern table",intro:"Bengali cooking centres on rice, fish, seasonal vegetables, mustard and a celebrated sweet tradition.",facts:["Fish curries and vegetable dishes use mustard oil and spice blends.","Shorshe, a mustard preparation, is a distinct regional flavour.","Mishti doi and sandesh are classic sweets."]},
  "Karnataka meals":{label:"South · Karnataka",intro:"Karnataka food ranges from millet-based inland meals to Udupi vegetarian cooking and coastal seafood traditions.",facts:["Bisi bele bath combines rice, lentils, vegetables and spice.","Ragi mudde and jolada rotti reflect northern Karnataka’s grain traditions.","Neer dosa and Mysore pak are favourites from different parts of the state."]},
  Bharatanatyam:{label:"Tamil Nadu",intro:"Bharatanatyam is a classical dance form known for sculptural poses, rhythmic footwork, expressive gestures and Carnatic music.",facts:["Its vocabulary combines nritta, or pure dance, with expressive storytelling.","Mudras and facial expression help communicate characters and emotions.","It is closely associated with Tamil Nadu’s artistic traditions."]},
  Kathak:{label:"North India",intro:"Kathak is a northern Indian classical dance form celebrated for rapid spins, rhythmic footwork and narrative expression.",facts:["Its name is linked to kathakas, traditional storytellers.","Ghungroo ankle bells accent the complex rhythmic patterns.","Styles developed through temple, court and contemporary performance traditions."]},
  Kuchipudi:{label:"Andhra Pradesh",intro:"Kuchipudi is a classical dance form from Andhra Pradesh that combines graceful movement, music, drama and storytelling.",facts:["It developed in the village of Kuchipudi.","Dance dramas and solo performance both have important roles.","Some performances include the famous brass-plate tarangam sequence."]},
  Kathakali:{label:"Kerala",intro:"Kathakali is Kerala’s dance-drama tradition, instantly recognised for its detailed makeup, costumes and powerful storytelling.",facts:["Stories are often drawn from the Ramayana and Mahabharata.","Facial expression, hand gestures and percussion are central to performance.","Costumes and colour codes help identify character types."]},
  Odissi:{label:"Odisha",intro:"Odissi is a classical dance from Odisha known for its flowing torso movements, sculptural lines and devotional repertoire.",facts:["The tribhangi posture creates a distinctive three-bend body line.","Its imagery connects deeply with Odisha’s temple and sculpture traditions.","Music and abhinaya bring devotional stories to life."]},
  Manipuri:{label:"Manipur",intro:"Manipuri is a gentle, lyrical classical dance tradition associated with the cultural landscape of Manipur.",facts:["Ras Lila performances are among its best-known forms.","Movement is often rounded, flowing and restrained in expression.","Costumes and music reflect local Vaishnav traditions."]},
  Mohiniyattam:{label:"Kerala",intro:"Mohiniyattam is a Kerala classical dance form known for graceful swaying movement and expressive storytelling.",facts:["The name refers to Mohini, the enchanting form of Vishnu.","White and gold costume styling is a recognisable visual signature.","Its repertoire combines delicate rhythm with lyrical abhinaya."]},
  Sattriya:{label:"Assam",intro:"Sattriya is Assam’s classical dance tradition, developed in Vaishnav monasteries called satras and now performed on stages worldwide.",facts:["It grew from devotional practices initiated by saint-scholar Sankaradeva.","Music, drama, costume and dance work together in its storytelling.","Both solo and group forms are performed today."]}
};

const cardSelector=".culture-photo-card,.food-grid article,.dance-gallery article";
const dialog=document.createElement("dialog");
dialog.className="culture-dialog";
dialog.innerHTML='<button class="culture-dialog-close" type="button" aria-label="Close guide">×</button><div class="culture-dialog-inner"><img class="culture-dialog-image" alt=""><div class="culture-dialog-copy"><p class="eyebrow"></p><h2></h2><p class="culture-dialog-intro"></p><h3>What to look for</h3><ul></ul></div></div>';
document.body.append(dialog);
const closeDialog=()=>dialog.close();
dialog.querySelector("button").addEventListener("click",closeDialog);
dialog.addEventListener("click",event=>{if(event.target===dialog)closeDialog()});

document.querySelectorAll(cardSelector).forEach(card=>{const title=card.querySelector("h3")?.textContent.trim(),detail=cultureDetails[title];if(!detail)return;card.classList.add("culture-card-interactive");card.tabIndex=0;card.setAttribute("role","button");card.setAttribute("aria-label",`Open ${title} guide`);const open=()=>{const image=card.querySelector("img"),dialogImage=dialog.querySelector("img"),facts=dialog.querySelector("ul");dialogImage.src=image?.src||"";dialogImage.alt=image?.alt||title;dialog.querySelector(".eyebrow").textContent=detail.label;dialog.querySelector("h2").textContent=title;dialog.querySelector(".culture-dialog-intro").textContent=detail.intro;facts.replaceChildren(...detail.facts.map(fact=>Object.assign(document.createElement("li"),{textContent:fact})));dialog.showModal();dialog.querySelector("button").focus()};card.addEventListener("click",open);card.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();open()}})});
