const destinationCoordinates={
  "andhra-pradesh":[15.91,79.74],"arunachal-pradesh":[27.1,93.6],assam:[26.2,92.9],bihar:[25.1,85.3],chhattisgarh:[21.3,81.9],goa:[15.3,74.1],gujarat:[22.3,71.2],haryana:[29.1,76.1],"himachal-pradesh":[31.1,77.2],jharkhand:[23.6,85.3],karnataka:[15.3,75.7],kerala:[10.85,76.27],"madhya-pradesh":[23.47,77.94],maharashtra:[19.75,75.7],manipur:[24.66,93.9],meghalaya:[25.47,91.36],mizoram:[23.16,92.94],nagaland:[26.15,94.56],odisha:[20.95,85.1],punjab:[31.1,75.3],rajasthan:[26.9,73.7],sikkim:[27.5,88.5],"tamil-nadu":[11.1,78.6],telangana:[17.9,79.1],tripura:[23.94,91.98],"uttar-pradesh":[26.8,80.9],uttarakhand:[30.1,79],"west-bengal":[22.98,87.85],"andaman-nicobar":[11.74,92.65],chandigarh:[30.73,76.78],"dadra-nagar-haveli-daman-diu":[20.3,73],delhi:[28.61,77.21],"jammu-kashmir":[33.4,75.5],ladakh:[34.15,77.58],lakshadweep:[10.56,72.64],puducherry:[11.94,79.8]
};
const weatherLabels={0:"Clear sky",1:"Mostly clear",2:"Partly cloudy",3:"Overcast",45:"Foggy",48:"Foggy",51:"Light drizzle",53:"Drizzle",55:"Heavy drizzle",61:"Light rain",63:"Rain",65:"Heavy rain",71:"Light snow",73:"Snow",75:"Heavy snow",80:"Rain showers",81:"Rain showers",82:"Heavy showers",95:"Thunderstorms"};
const slugForLive=new URLSearchParams(location.search).get("slug"),coordinateForLive=destinationCoordinates[slugForLive];
const loadLeaflet=()=>window.L?Promise.resolve():new Promise((resolve,reject)=>{const existing=document.querySelector('script[data-leaflet]');if(existing){existing.addEventListener("load",resolve,{once:true});existing.addEventListener("error",reject,{once:true});return}const css=document.createElement("link"),script=document.createElement("script");css.rel="stylesheet";css.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";script.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";script.dataset.leaflet="true";script.onload=resolve;script.onerror=reject;document.head.append(css,script)});
const createPanel=()=>{const section=document.createElement("section");section.className="live-explorer";section.setAttribute("aria-label","Live weather and destination map");section.innerHTML='<div class="live-explorer-heading"><div><p class="eyebrow">Live travel view</p><h2>Weather and map</h2></div><p class="live-source">Weather by Open-Meteo · Map by OpenStreetMap</p></div><div class="live-explorer-grid"><article class="weather-panel"><span>Current conditions</span><p class="live-loading">Loading live weather…</p></article><div class="destination-map" aria-label="Interactive destination map"></div></div>';return section};
const renderWeather=(panel,current)=>{const unit=current.temperature_2m_unit||"°C",windUnit=current.wind_speed_10m_unit||"km/h",code=current.weather_code;panel.innerHTML=`<span>Current conditions</span><strong>${Math.round(current.temperature_2m)}${unit}</strong><p>${weatherLabels[code]||"Local conditions"}</p><div class="weather-meta"><span>Feels like ${Math.round(current.apparent_temperature)}${unit}</span><span>Wind ${Math.round(current.wind_speed_10m)} ${windUnit}</span></div>`};
async function initLiveExplorer(){if(!coordinateForLive)return;const section=createPanel(),anchor=document.querySelector(".travel-actions")||document.querySelector(".detail-grid");if(!anchor)return;anchor.after(section);const [lat,lon]=coordinateForLive,panel=section.querySelector(".weather-panel");try{const weather=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=auto`).then(reply=>{if(!reply.ok)throw new Error("weather unavailable");return reply.json()});renderWeather(panel,weather.current)}catch{panel.innerHTML='<span>Current conditions</span><p class="live-loading">Weather is unavailable right now. Please try again later.</p>'}try{await loadLeaflet();const map=window.L.map(section.querySelector(".destination-map"),{scrollWheelZoom:false}).setView([lat,lon],6);window.L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);window.L.marker([lat,lon]).addTo(map).bindPopup(`${slugForLive.replaceAll("-"," ")}`).openPopup()}catch{section.querySelector(".destination-map").innerHTML='<p class="live-loading">Map is unavailable right now.</p>'}}
initLiveExplorer();
