const slug=new URLSearchParams(location.search).get('slug');
const make=(tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;};
const date=value=>{const parsed=new Date(String(value||'').replace(' ','T')+'Z');return Number.isNaN(parsed.getTime())?'':new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'}).format(parsed);};
async function loadReviews(){
 if(!slug)return;const anchor=document.querySelector('.live-explorer')||document.querySelector('#practical');if(!anchor)return;
 let section=document.querySelector('.reviews-section');if(!section){section=make('section',undefined,'reviews-section');anchor.after(section);}
 const [response,sessionResponse]=await Promise.all([fetch(`/api/destinations/${encodeURIComponent(slug)}/reviews`),fetch('/api/auth/me')]);if(!response.ok){section.textContent='Reviews are unavailable right now.';return;}
 const data=await response.json(),session=sessionResponse.ok?(await sessionResponse.json()).data:null;
 section.replaceChildren(make('h2','Traveller reviews'),make('p',data.summary.count?`${data.summary.averageRating} / 5 from ${data.summary.count} review(s)`:'No published reviews yet. Reviews appear after moderation.'));
 if(data.ownReview)section.append(make('p',`Your review status: ${data.ownReview.status}.`));
 const list=make('div',undefined,'reviews-list');section.append(list);
 for(const review of data.data){const card=make('article',undefined,'review-card');card.append(make('strong',review.author),make('span',` · ${review.rating}/5 stars`),make('p',review.comment),make('small',date(review.updatedAt||review.createdAt)));
  if(session){const report=make('button','Report this review','button');report.type='button';report.addEventListener('click',async()=>{const reason=prompt('Report reason: spam, offensive, misleading, privacy or other');if(reason===null)return;const result=await fetch(`/api/reviews/${review.id}/reports`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:reason.trim().toLowerCase()})});report.textContent=result.ok?'Report sent':'Could not report; choose one of the listed reasons.';});card.append(report);}list.append(card);}
 if(!session)return;const form=make('form',undefined,'review-form');const heading=make('h3','Share your experience');const ratingLabel=make('label','Rating');const rating=make('select');rating.name='rating';for(let n=5;n>=1;n--){const option=make('option',`${n} stars`);option.value=String(n);rating.append(option);}ratingLabel.append(rating);const commentLabel=make('label','Your review');const comment=make('textarea');comment.name='comment';comment.required=true;comment.minLength=20;comment.maxLength=600;comment.value=data.ownReview?.comment||'';commentLabel.append(comment);const submit=make('button','Submit for moderation','button button-primary');submit.type='submit';const message=make('p',undefined,'review-form-message');message.setAttribute('role','status');form.append(heading,ratingLabel,commentLabel,submit,message);section.append(form);form.addEventListener('submit',async event=>{event.preventDefault();submit.disabled=true;try{const result=await fetch(`/api/destinations/${encodeURIComponent(slug)}/reviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating:Number(rating.value),comment:comment.value})});const body=await result.json();if(!result.ok)throw Error(body.error||'Could not save your review.');await loadReviews();}catch(error){message.textContent=error.message;}finally{submit.disabled=false;}});
}
document.addEventListener('destination:ready',()=>loadReviews().catch(()=>{}),{once:true});
