const form=document.querySelector('#tripForm'), choices=document.querySelector('#destinationChoices'), status=document.querySelector('#tripStatus'), preview=document.querySelector('#tripPreview'), daysBox=document.querySelector('#previewDays'), list=document.querySelector('#plansList');
let destinations=[], editing=null, current=null;
const interests=['heritage','food','nature','art','relaxation'];
const say=message=>{status.hidden=false;status.textContent=message;};
const request=async(path,options={})=>{const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});const body=response.status===204?{}:await response.json().catch(()=>({}));if(!response.ok)throw Error(body.error||'Request failed. Please try again.');return body.data;};
const node=(tag,text,cls)=>{const element=document.createElement(tag);if(text!==undefined)element.textContent=text;if(cls)element.className=cls;return element;};
for(const value of interests){const label=node('label');const input=document.createElement('input');input.type='checkbox';input.name='interests';input.value=value;label.append(input,document.createTextNode(value[0].toUpperCase()+value.slice(1)));document.querySelector('#interests').append(label);}
const payload=()=>{const data=new FormData(form);return {title:String(data.get('title')||''),origin:String(data.get('origin')||''),startDate:String(data.get('startDate')||''),days:Number(data.get('days')),budget:Number(data.get('budget')),pace:String(data.get('pace')),transport:String(data.get('transport')),interests:data.getAll('interests'),destinationIds:[...choices.querySelectorAll('input:checked')].map(input=>Number(input.value))};};
const renderChoices=selected=>{choices.replaceChildren();[...selected.map(id=>destinations.find(destination=>destination.id===id)).filter(Boolean),...destinations.filter(destination=>!selected.includes(destination.id))].forEach(destination=>{const label=node('label');const input=document.createElement('input');input.type='checkbox';input.value=destination.id;input.checked=selected.includes(destination.id);label.append(input,document.createTextNode(destination.name));choices.append(label);});};
const showDays=(plan,editable=false)=>{current=plan;preview.hidden=false;daysBox.replaceChildren();document.querySelector('#previewWarning').textContent=(plan.warnings||[]).join(' ');for(const day of plan.itinerary||[]){const card=node('article',undefined,'planner-day');card.dataset.day=String(day.day);card.append(node('h3',`Day ${day.day} · ${day.date} · ${day.destination}`));for(const field of ['title','morning','afternoon','evening','notes']){const label=node('label',field[0].toUpperCase()+field.slice(1));const input=document.createElement(field==='title'?'input':'textarea');input.name=field;input.value=day[field]||'';input.readOnly=!editable;input.maxLength=field==='title'?160:700;label.append(input);card.append(label);}if(day.type==='transfer')card.append(node('p','Transfer day: check actual connections before booking.'));if(day.sources?.length){const link=node('a','Destination source ↗');link.href=day.sources[0].url;link.target='_blank';link.rel='noopener noreferrer';card.append(link);}daysBox.append(card);}if(editable){const save=node('button','Save day edits','button button-primary');save.type='button';save.onclick=saveEdits;daysBox.append(save);}preview.scrollIntoView({block:'start',behavior:'smooth'});};
const editedItinerary=()=>current.itinerary.map((day,index)=>{const card=daysBox.querySelectorAll('.planner-day')[index];return {...day,...Object.fromEntries(['title','morning','afternoon','evening','notes'].map(field=>[field,card.querySelector(`[name="${field}"]`).value]))};});
async function saveEdits(){try{const plan=await request(`/api/trip-plans/${editing}`,{method:'PATCH',body:JSON.stringify({...payload(),itinerary:editedItinerary()})});say('Day edits saved.');showDays(plan,true);await loadPlans();}catch(error){say(error.message);}}
async function loadPlans(){const plans=await request('/api/trip-plans');list.replaceChildren();document.querySelector('#plansEmpty').hidden=plans.length>0;for(const plan of plans){const card=node('article',undefined,'saved-trip');card.append(node('h3',plan.title),node('p',`${plan.days} days · ${plan.destinationNames.join(' → ')} · ${plan.startDate||plan.travelMonth}`));const button=(label,action)=>{const element=node('button',label,'button');element.type='button';element.onclick=action;card.append(element);};button('Open & edit',()=>openPlan(plan));button('Print',()=>{showDays(plan,false);window.print();});button('Share',async()=>{if(!confirm('Anyone with the link can read this itinerary and its notes. Create a public link?'))return;try{const data=await request(`/api/trip-plans/${plan.id}/share`,{method:'POST',body:JSON.stringify({confirmPublic:true})});const url=new URL(data.path,location.href).href;await navigator.clipboard.writeText(url);say('Share link copied. It can be revoked from this plan.');await loadPlans();}catch(error){say(error.message);}});if(plan.sharingEnabled)button('Revoke share',async()=>{try{await request(`/api/trip-plans/${plan.id}/share`,{method:'DELETE'});say('Share link revoked.');await loadPlans();}catch(error){say(error.message);}});button('Delete',async()=>{if(!confirm(`Delete ${plan.title}?`))return;try{await request(`/api/trip-plans/${plan.id}`,{method:'DELETE'});say('Trip deleted.');await loadPlans();}catch(error){say(error.message);}});list.append(card);}};
function openPlan(plan){editing=plan.id;form.elements.title.value=plan.title;form.elements.origin.value=plan.origin||'';form.elements.startDate.value=plan.startDate||`${plan.travelMonth}-01`;form.elements.days.value=plan.days;form.elements.budget.value=plan.budget;form.elements.pace.value=plan.pace;form.elements.transport.value=plan.transport;renderChoices(plan.destinationIds);for(const checkbox of document.querySelectorAll('#interests input'))checkbox.checked=plan.interests.includes(checkbox.value);document.querySelector('#formTitle').textContent='Edit trip';document.querySelector('#saveTrip').textContent='Save trip changes';document.querySelector('#cancelEdit').hidden=false;showDays(plan,true);}
document.querySelector('#cancelEdit').onclick=()=>{editing=null;form.reset();renderChoices([]);preview.hidden=true;document.querySelector('#formTitle').textContent='Your trip';document.querySelector('#saveTrip').textContent='Save trip';document.querySelector('#cancelEdit').hidden=true;};
document.querySelector('#previewTrip').onclick=async()=>{try{showDays(await request('/api/trip-plans/preview',{method:'POST',body:JSON.stringify(payload())}));say('Preview ready. Save the trip to edit its days.');}catch(error){say(error.message);}};
form.addEventListener('submit',async event=>{event.preventDefault();try{const data=payload();const plan=editing?await request(`/api/trip-plans/${editing}`,{method:'PATCH',body:JSON.stringify(data)}):await request('/api/trip-plans',{method:'POST',body:JSON.stringify(data)});editing=plan.id;say('Trip saved. You can edit the day-by-day plan below.');showDays(plan,true);await loadPlans();}catch(error){say(error.message);}});
async function init(){const share=new URLSearchParams(location.search).get('share');if(share){form.hidden=true;document.querySelector('.plans-section').hidden=true;try{showDays(await request(`/api/shared-trips/${encodeURIComponent(share)}`));}catch(error){say(error.message);}return;}try{const me=await request('/api/auth/me');if(!me){form.hidden=true;say('Sign in to plan and save a trip.');const link=node('a','Sign in');link.href='auth.html';status.append(' ',link);return;}destinations=(await request('/api/destinations')).slice().sort((a,b)=>a.name.localeCompare(b.name));const saved=await request('/api/favourites').catch(()=>[]);renderChoices(saved.map(item=>item.id));form.elements.startDate.value=new Date(Date.now()+86400000).toISOString().slice(0,10);await loadPlans();}catch(error){say(error.message);}}
init();
