if(location.pathname.endsWith("/culture.html")){const style=document.createElement("link"),script=document.createElement("script");style.rel="stylesheet";style.href="culture.css";script.src="culture.js";document.head.append(style);document.body.append(script)}if(location.pathname.endsWith("/destination.html")){const style=document.createElement("link"),live=document.createElement("script"),reviews=document.createElement("script");style.rel="stylesheet";style.href="destination-live.css";live.src="destination-live.js";reviews.src="destination-reviews.js";document.head.append(style);document.body.append(live,reviews)}if(location.pathname.endsWith("/about.html")){const style=document.createElement("link"),script=document.createElement("script");style.rel="stylesheet";style.href="about-profile.css";script.src="about-profile.js";document.head.append(style);document.body.append(script)}
const header=document.querySelector("[data-header]"),toggle=document.querySelector(".nav-toggle"),navigation=document.querySelector(".primary-nav");
const updateHeader=()=>header?.classList.toggle("scrolled",scrollY>24);updateHeader();addEventListener("scroll",updateHeader,{passive:true});
toggle?.addEventListener("click",()=>{const open=toggle.getAttribute("aria-expanded")==="true";toggle.setAttribute("aria-expanded",String(!open));navigation?.classList.toggle("open",!open);document.body.classList.toggle("nav-open",!open)});
navigation?.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>{toggle?.setAttribute("aria-expanded","false");navigation.classList.remove("open");document.body.classList.remove("nav-open")}));
const footerNavigation=document.querySelector(".site-footer nav");
footerNavigation?.append(Object.assign(document.createElement("a"),{href:"about.html",textContent:"About this project"}),Object.assign(document.createElement("a"),{href:"admin.html",textContent:"Admin access"}));

fetch("/api/auth/me").then(response=>response.ok?response.json():null).then(result=>{if(!navigation)return;const user=result?.data,links=user?.role==="admin"?[["admin.html","Admin"]]:user?[["favourites.html","Saved"],["planner.html","Plan a trip"],["profile.html","Profile"]]:[["auth.html","Sign in"]];links.forEach(([href,label])=>{const link=document.createElement("a");link.href=href;link.textContent=label;navigation.append(link)})}).catch(()=>{});
