const searchInput=document.querySelector("#searchInput"),regionFilter=document.querySelector("#regionFilter"),clearFilters=document.querySelector("#clearFilters"),grid=document.querySelector("#statesGrid"),resultCount=document.querySelector("#resultCount"),emptyState=document.querySelector("#emptyState");
const regionLabels={north:"North India",south:"South India",east:"East India",west:"West India",central:"Central India",northeast:"Northeast India"};
const fallbackCards=[...grid.querySelectorAll(".destination-card")];let timer,account=null,favouriteIds=new Set;
function favouriteButton(item){const button=document.createElement("button"),saved=favouriteIds.has(item.id);button.type="button";button.className=`favourite-button${saved?" saved":""}`;button.dataset.favourite=item.id;button.setAttribute("aria-pressed",String(saved));button.setAttribute("aria-label",`${saved?"Remove":"Save"} ${item.name}`);button.textContent=saved?"♥ Saved":"♡ Save";return button}
function createCard(item){const article=document.createElement("article");article.className="destination-card destination-link-card";article.dataset.region=item.region;article.tabIndex=0;article.setAttribute("role","link");article.setAttribute("aria-label",`Explore ${item.name}`);let visual;if(item.imagePath){visual=document.createElement("img");visual.src=item.imagePath;visual.alt=item.imageAlt;visual.loading="lazy"}else{visual=document.createElement("div");visual.className=`destination-placeholder region-${item.region}`;visual.setAttribute("aria-hidden","true");visual.textContent=item.name.split(/\s|&/).filter(Boolean).slice(0,2).map(word=>word[0]).join("")}const content=document.createElement("div"),region=document.createElement("span"),title=document.createElement("h3"),summary=document.createElement("p"),detail=document.createElement("a");region.textContent=regionLabels[item.region]||item.region;title.textContent=item.name;summary.textContent=item.summary;detail.href=`destination.html?slug=${encodeURIComponent(item.slug)}`;detail.className="destination-detail-link";detail.textContent="Explore place →";content.append(region,title,summary,detail);article.append(visual,content);if(account)article.append(favouriteButton(item));article.addEventListener("keydown",event=>{if((event.key==="Enter"||event.key===" ")&&event.target===article){event.preventDefault();location.href=detail.href}});return article}
function showFallback(){const term=searchInput.value.trim().toLowerCase(),selected=regionFilter.value;let visible=0;fallbackCards.forEach(card=>{const show=card.textContent.toLowerCase().includes(term)&&(selected==="all"||card.dataset.region===selected);card.hidden=!show;if(show)visible++});resultCount.textContent=`${visible} destination${visible===1?"":"s"} · offline catalogue`;emptyState.hidden=visible!==0}
async function loadDestinations(){resultCount.textContent="Loading destinations…";const params=new URLSearchParams();if(searchInput.value.trim())params.set("q",searchInput.value.trim());if(regionFilter.value!=="all")params.set("region",regionFilter.value);try{const response=await fetch(`/api/destinations?${params}`);if(!response.ok)throw new Error("Catalogue unavailable");const result=await response.json();grid.replaceChildren(...result.data.map(createCard));resultCount.textContent=`${result.count} destination${result.count===1?"":"s"}`;emptyState.hidden=result.count!==0}catch{if(!fallbackCards.some(card=>card.isConnected))grid.replaceChildren(...fallbackCards);showFallback()}}
async function updateFavourite(button){if(!account){window.location.href="auth.html";return}const destinationId=Number(button.dataset.favourite),saved=favouriteIds.has(destinationId);button.disabled=true;try{const response=await fetch(`/api/favourites/${destinationId}`,{method:saved?"DELETE":"POST"});if(!response.ok)throw new Error("Unable to update saved destination");saved?favouriteIds.delete(destinationId):favouriteIds.add(destinationId);button.classList.toggle("saved",!saved);button.setAttribute("aria-pressed",String(!saved));button.setAttribute("aria-label",`${saved?"Save":"Remove"} destination`);button.textContent=saved?"♡ Save":"♥ Saved"}catch{button.textContent="Try again"}finally{button.disabled=false}}
function queueLoad(){clearTimeout(timer);timer=setTimeout(loadDestinations,180)}
searchInput.addEventListener("input",queueLoad);regionFilter.addEventListener("change",loadDestinations);clearFilters.addEventListener("click",()=>{searchInput.value="";regionFilter.value="all";loadDestinations();searchInput.focus()});grid.addEventListener("click",event=>{const button=event.target.closest("[data-favourite]");if(button)updateFavourite(button)});fetch("/api/auth/me").then(response=>response.json()).then(async session=>{account=session.data;if(account){const favourites=await fetch("/api/favourites").then(response=>response.ok?response.json():null);favouriteIds=new Set((favourites?.data||[]).map(item=>item.id))}loadDestinations()}).catch(loadDestinations);
